### ISSUE TITLE
Server Files have an extra mod. 

### ISSUE THREAD

**Issue by AzureDoom** [antibang/BaerCraft#4]
**Describe the Bug**
The server can not be connected to with the client using the provided server files on CurseForge. This is due to Ma-Essentials being on the server but not the client. Removing this allows the client to connect normally. Found via working with the modpack via BisectHosting servers and checking your local files. If you have any other questions, feel free to reach out to me at `AzureDoom#3690` on discord as I handle the modpacks for BisectHosting! 

**To Reproduce**
Run server and try to connect.

**Comment by antibang** [comment]
Yup! I’m glad you joined the Discord and mentioned this because it seems GitHub opted me out of all notifications… 

Anyways, thanks for bringing this my attention. I did fix this immediately after you mentioned it. Additionally, I will looking into adopting another efficient method to create server packs to avoid this in the future :)
